# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    machine: true
    docker:
      - image: lllonely010/mypython:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker run --name testsuite .
      - run: docker cp testsuite:/home/mypython .
      - run: cd /opt/mypython/workspace && pytest -v --no-summary --html=/workspace/reports/report.html --self-contained-html pythonapi

 

